version: '3.7'

services:
  web:
    environment:
      - PROD=true
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    env_file:
      - ./config/.env.prod
    volumes:
      - ./config/awsproviderstate.json:/etc/awsproviderstate.json