version: '3.7'

services:
  web:
    env_file:
      - ./config/.env.prod
    volumes:
      - ./config/awsproviderstate.json:/etc/awsproviderstate.json
  worker:
    env_file:
      - ./config/.env.prod
    volumes:
      - ./config/awsproviderstate.json:/etc/awsproviderstate.json